### ISSUE TITLE
trouble setting up .env variables

### ISSUE THREAD

**Issue by cityji** [MrJerif/LockCraft#1]
Hi, thanks for this wonderful project, 
i truely admire it, i was myself building  a similar project from scratch but goot carried away, 

frankly i am not that expert in development, just starting out.

exact issue : 
`_when i try to login_ :  **it redirects me to a blank page** 
https://undefined/authorize?scope=openid+read%3Acurrent_user+update%3Acurrent_user_metadata+profile+email&redirect_uri=http%3A%2F%2Flocalhost%3A5173&audience=lockcraftpasswordmanager%2Fidentifier&response_type=code&response_mode=query&state=eHNEZEc2UFY5SmZ4ZkWEwUWQzRnpQZmRtWDhsQTJpcg%3D%3D&nonce=Z1hfMnZGeTdSSUxiS09Qd0VPa0lSN0htTEcwa19VU5RQ%3D%3D&code_challenge=tMF2aGmJSDnTSN85jRvd=DlPFVDA__JLid3A&code_challenge_method=S256&auth0Client=eyJuYW1lIjoiYXV0aDAtcmVhY3QiLCJLjQifQ%3D%3D
`

**Console Log : **
```

chunk-M7F2YF5A.js?v=40eb090d:521 Warning: Invalid DOM property `stroke-width`. Did you mean `strokeWidth`?
    at path
    at svg
    at div
    at nav
    at NavbarGenerate
    at Generate (http://localhost:5173/src/components/Generate.jsx:27:31)
    at RenderedRoute (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=fe2a8c1b:4028:5)
    at Routes (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=fe2a8c1b:4467:5)
    at main
    at App (http://localhost:5173/src/App.jsx:29:49)
    at Auth0Provider (http://localhost:5173/node_modules/.vite/deps/@auth0_auth0-react.js?v=b7214b3a:1197:23)
    at Router (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=fe2a8c1b:4410:15)
    at BrowserRouter (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=fe2a8c1b:5155:5)

chunk-M7F2YF5A.js?v=40eb090d:521 Warning: Invalid DOM property `stroke-linecap`. Did you mean `strokeLinecap`?
    at path
    at svg
    at div
    at nav
    at NavbarGenerate
    at Generate (http://localhost:5173/src/components/Generate.jsx:27:31)
    at RenderedRoute (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=fe2a8c1b:4028:5)
    at Routes (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=fe2a8c1b:4467:5)
    at main
    at App (http://localhost:5173/src/App.jsx:29:49)
    at Auth0Provider (http://localhost:5173/node_modules/.vite/deps/@auth0_auth0-react.js?v=b7214b3a:1197:23)
    at Router (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=fe2a8c1b:4410:15)
    at BrowserRouter (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=fe2a8c1b:5155:5)
chunk-M7F2YF5A.js?v=40eb090d:521 Warning: Invalid DOM property `stroke-linejoin`. Did you mean `strokeLinejoin`?
    at path
    at svg
    at div
    at nav
    at NavbarGenerate
    at Generate (http://localhost:5173/src/components/Generate.jsx:27:31)
    at RenderedRoute (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=fe2a8c1b:4028:5)
    at Routes (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=fe2a8c1b:4467:5)
    at main
    at App (http://localhost:5173/src/App.jsx:29:49)
    at Auth0Provider (http://localhost:5173/node_modules/.vite/deps/@auth0_auth0-react.js?v=b7214b3a:1197:23)
    at Router (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=fe2a8c1b:4410:15)
    at BrowserRouter (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=fe2a8c1b:5155:5)
﻿

```
okay so i think I was having a issue adding the necessary environment variables:

done AUTH0_DOMAIN=your_auth0_domain 
AUTH0_AUDIENCE=your_auth0_audience    `not sure if you're refering to "Client ID"? `
MONGO_URI=your_mongo_uri                      
ENCRYPTION_KEY=your_encryption_key   ?? `how to setup this? where do i get this?`
PORT=5000

i have worked as fromt end till now, i'm learning backend it will be a great
if you could assist a little 

Thanks again 👍🏻

**Comment by MrJerif** [comment]
Hi Nikhil! I'm glad you liked my project..
For backend Your .ENV file must have
1. ATH0_AUDIENCE
2. ATUH0_CLIENT_ID (Check your project on auth0 dashboard)
3. AUTH0_DOMAIN
4. CORS_ORIGIN
5. ENCRYPTION_KEY (You have to generate Random 32-byte key, below i will
provide you steps)
6. MONGO_URI

Steps to Generate Encryption key
1.  Create a backend file e,g " generate.js "
2. Write below provided Express JS code in that file

     const crypto = require('crypto');

     const key = crypto.randomBytes(32).toString('hex');
     console.log(key);

3. Run the command  'node [yourfilename] ' e,g ( node generate.js ) in your
terminal
4. You should be able to see the generated key, just copy it and past it in
your .ENV file.

and that's it.... Hope this will help.
Enjoy coding ✌️👍

**Comment by cityji** [comment]
Thanks For Reply I really appreciate it, 
still i'am unable to get it working,  [please help me set it up]

i am getting this on backend console log: 
I've alredy whitelisted my ip from n/w access of mongodb url 


``` 
npm start

> backend@1.0.0 start
> node server.js

Server running on 5000
Mongoose disconnected from mongoDB
MongoDB connection error  MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/
    at _handleConnectionErrors (/media/noob/Data/Projects/LockCraft/backend/node_modules/mongoose/lib/connection.js:900:11)
    at NativeConnection.openUri (/media/noob/Data/Projects/LockCraft/backend/node_modules/mongoose/lib/connection.js:851:11) {
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    servers: Map(3) {
      'passwordwale-shard-00-00.xprsb.mongodb.net:27017' => [ServerDescription],
      'passwordwale-shard-00-02.xprsb.mongodb.net:27017' => [ServerDescription],
      'passwordwale-shard-00-01.xprsb.mongodb.net:27017' => [ServerDescription]
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: 'atlas-k1x2cx-shard-0',
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined
}
```


i wanted to share a bit more info, it would be really amazing if i can connect to you anywhere like discord,telegram
would mind sharing any socials?

or just ping me

**Comment by MrJerif** [comment]
Hey Nikhil! Sorry for the late reply, I was busy and missed the notification.
Let's talk about your issue, The disconnection issue is because your IP address is not whitelisted to access the database. 
If you are using Render for the frontend as i did for this project, you need to specify Render IP range to access the database unfortunately Render don't provide static IP range so you can simply allow all i.e **0.0.0.0/0** (IP block containing all possible IP addresses), and this will resolve your issue, **however** it is not a good option for production use but for projects it's fine.
For more information on this issue " https://community.render.com/t/ip-ranges-to-use-for-whitelisting/1528 "

**Comment by cityji** [comment]
Hi, Thanks for your response,
I know you must be busy, 

I already did that
and tried all possible trobulshooting i could ( in my tiny knowledge area)  :  

that issue is still there, 
![Screenshot from 2024-11-15 00-01-18](https://github.com/user-attachments/assets/acb39458-5db5-436e-baf2-5c3a7739843b)

**can we communicate over reddit?**
i've pinged you there,
